name = "techconf-directory"
compatibility_date = "2026-01-20"
workers_dev = false
preview_urls = false

[assets]
directory = "./build/"
not_found_handling = "404-page"
html_handling = "drop-trailing-slash"
